### ISSUE TITLE
cannot load such file -- acl9/controller_extensions (LoadError)

### ISSUE THREAD

**Issue by richcfml** [be9/acl9#101]
Hello,

I am getting this error when I am trying to use ACL9 on RedHat 6 with Passenger. I saw a similar error posted before but no solution except that you guys couldn't replicated. The issue was raised about 27 days ago and the response was a week ago.

I am having the same exact problem and I have double check everything in my system and everything looks fine. the controller_extensions file and directory are all there.

I have installed Ruby 2.2.3 using RVM and I am using Rails 4.2.4

I will be glad to provide as much information as requested to see if there is a problem here or something else.

Thank you for your prompt attention

**Comment by richcfml** [comment]
Corrected

**Comment by smathy** [comment]
Can you tell me how this was corrected because I recently had precisely the same error reported by someone deploying to Amazon Beanstalk - #100

**Comment by richcfml** [comment]
Hello smathy,

I thought I had it corrected. The error started when I tried to migrate my DB migration files. Then it when away for a while during my upgrade of Apache from 2.2.15 to 2.4 but when I restarted the web server the error still there when I try to load the application. However, I am using now Apache 2.4 with Phusion Passenger 5.

Here is the error log that I am getting
Message from application: cannot load such file -- acl9/controller_extensions (LoadError)
  /usr/local/rvm/gems/ruby-2.2.3/gems/acl9-2.1.1/lib/acl9.rb:3:in `require'
  /usr/local/rvm/gems/ruby-2.2.3/gems/acl9-2.1.1/lib/acl9.rb:3:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
  /usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
  /usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
  /usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
  /usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
  /usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
  /usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
  /var/www/html/clovermenu/code/config/application.rb:16:in `<top (required)>'
  /var/www/html/clovermenu/code/config/environment.rb:2:in `require'
  /var/www/html/clovermenu/code/config/environment.rb:2:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /usr/local/rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
  /usr/local/rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.0.26/src/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.0.26/src/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.0.26/src/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.0.26/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.0.26/src/helper-scripts/rack-preloader.rb:29:in `<main>'

**Comment by smathy** [comment]
Can you give me the output of `gem environment` on your server.

**Comment by richcfml** [comment]
Sure,

RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.8
  - RUBY VERSION: 2.2.3 (2015-08-18 patchlevel 173) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/rvm/gems/ruby-2.2.3
  - RUBY EXECUTABLE: /usr/local/rvm/rubies/ruby-2.2.3/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/rvm/gems/ruby-2.2.3/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/rvm/rubies/ruby-2.2.3/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/local/rvm/gems/ruby-2.2.3
     - /usr/local/rvm/gems/ruby-2.2.3@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/rvm/gems/ruby-2.2.3/bin
     - /usr/local/rvm/gems/ruby-2.2.3@global/bin
     - /usr/local/rvm/rubies/ruby-2.2.3/bin
     - /usr/local/bin
     - /bin
     - /usr/bin
     - /usr/local/sbin
     - /usr/sbin
     - /sbin
     - /usr/local/rvm/bin
     - /home/myuser/bin

**Comment by smathy** [comment]
...and what's your `PassengerRuby` (or `PassengerDefaultRuby`) in your passenger config set to?

**Comment by richcfml** [comment]
Sure

PassengerRuby /usr/local/rvm/gems/ruby-2.2.3/wrappers/ruby

---------------------------------------------------------------
Richard Ardila
P: 404.798.3317

**Comment by smathy** [comment]
Hmm, so that's different to what is output as `RUBY EXECUTABLE` by `gem environment` which makes me wonder (I'm no rvm expert though).

Tell me what does `passenger-config about ruby-command` tell you to set `PassengerRuby` to?

**Comment by richcfml** [comment]
Sure,

Here it is

passenger-config was invoked through the following Ruby interpreter:
  Command: /usr/local/rvm/gems/ruby-2.2.3/wrappers/ruby
  Version: ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
  To use in Apache: PassengerRuby
/usr/local/rvm/gems/ruby-2.2.3/wrappers/ruby
  To use in Nginx : passenger_ruby
/usr/local/rvm/gems/ruby-2.2.3/wrappers/ruby
  To use with Standalone: /usr/local/rvm/gems/ruby-2.2.3/wrappers/ruby
/usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.0.26/bin/passenger start

---------------------------------------------------------------
Richard Ardila
P: 404.798.3317

**Comment by smathy** [comment]
All seems right, tell me, if you remove `acl9` from your `Gemfile`, do things then work? Or do you get the same error from a different gem?

**Comment by richcfml** [comment]
if I remove the acl9 from the Gemfile everything works just fine. The issue
here is that the application I am building is already using ACL9 in many
places so it may take me more time to replace it with another gem than
trying to figure this out. That is why I reach out. Besides, I like your
implementation and I would like to continue using it if possible.

---------------------------------------------------------------
Richard Ardila
P: 404.798.3317

**Comment by smathy** [comment]
Ohhh, I think I found it.

The file permissions on that file (and some others) is missing the world read bit. Let me push a new version for you, thanks for your patience and help.

**Comment by richcfml** [comment]
ok great, let me know.

---------------------------------------------------------------
Richard Ardila
P: 404.798.3317

**Comment by smathy** [comment]
Ok fixed, just `bundle update acl9` and redeploy and you should be good.

**Comment by richcfml** [comment]
ok thank you I will try it

---------------------------------------------------------------
Richard Ardila
P: 404.798.3317

**Comment by smathy** [comment]
All working now?
